services:
  - type: web
    name: lb-mecanica-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
