services:
  - type: web
    name: lb-mecanica-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: lb_mecanica_secret_2024_prod
